### ISSUE TITLE
stack dumping possible workaround

### ISSUE THREAD

**Issue by Kole6738** [aers/EngineFixesSkyrim64#2]
edit: AFAICT turns out save corruption due to stack dumping happens later on in the game - after the stack dump, which is apparently just a diagnostic. Patching the check seems like it will just prevent the diagnostic from firing, without actually correcting the base issue.

**Comment by Nukem9** [comment]
Can be found by searching for the string `Suspended stack count is over our warning threshold, dumping stacks:`

`if ( v6 + 5000 < v4 && *(_DWORD *)(v2 + 34724) + 60000 < v4 )`

I'm not sure if increasing these numbers will magically fix it. Leaving this here for any future reference though.

**Comment by ousnius** [comment]
Also, excessive stack dumping causes a crash in SE while it doesn't in LE.

**Comment by Kole6738** [comment]
I pretty much gave up on this after a few weeks; it turns out the process I was using was changing the size of the stack, but not in the way I was expecting it to. It was allocating more memory but it seems that the VM is pretty much hardcoded in a few places to only use a certain amount of memory, and it's gonna be a **huge** pain to patch all of the locations. Will be doing more research in the future perhaps but for now someone else can take the credit for doing it.

**Comment by Kole6738** [comment]
@Nukem9 I am a MORON. Disregard previous, Yeah, increasing the numbers would work fine as far as I can tell. Turns out patching the check to never fire the "Suspended stack" with a jmp and NOPs causes problems when you overwrite an extra byte with 0x90, but works fine otherwise.

**Comment by Kole6738** [comment]
> edit: AFAICT turns out save corruption due to stack dumping happens later on in the game - after the stack dump, which is apparently just a diagnostic. Patching the check seems like it will just prevent the diagnostic from firing, without actually correcting the base issue.
