### ISSUE TITLE
[SUGGESTION] Expand the BSA file size limit, if at all possible

### ISSUE THREAD

**Issue by Sunconure11** [aers/EngineFixesSkyrim64#30]
https://forums.nexusmods.com/index.php?/topic/9419188-apply-spell-patch/page-21#entry93177248

If this person is correct, then there appears to be a cutoff as to where the game simply won't load large BSA file sizes, and I'm sure it is probably easy to hit said limit, if it exists.

**Comment by Ryan-rsm-McKenzie** [comment]
This is impossible
