### ISSUE TITLE
When going from 5.6.0 to 5.7.0 it's not working.

### ISSUE THREAD

**Issue by ghyujkilop** [aers/EngineFixesSkyrim64#37]
I have ensured that the my settings from my old .toml were transferred over. As I have a backup of it.

What happens is my game loads, but I believe it skips something. I've experienced this before, and when I revert to the 5.6.0 it works again. The game loads too fast when I updated, I think it's skipping something.

Here's some pictures of what you'll find: 

5.6.0 pics - https://imgur.com/a/aFXnJaT
5.7.0 pics - https://imgur.com/a/PXvA32h

I've tried with & without the AnimatedStaticReload.dll. I have got the animation crash limit fix as well.

I think it's SKSE that's causing the issue. As this isn't updated for latest SKSE.

**Comment by BullOnMars** [comment]
You need to change Maxsdio from -1 to at least 2048 or 4096

**Comment by BullOnMars** [comment]
Throughly read on what's changed on github otherwise do not download if you don't know what u are doing, often user error results in blaming not working.

**Comment by ghyujkilop** [comment]
MY apologies, where did you see that suggestion? I can't see it on the main page or anything.

**Comment by BullOnMars** [comment]
5.6.1
MaxStdio is now configurable

**Comment by ghyujkilop** [comment]
Alright. But now I have a new issue, whenever I load a game I sometimes experience the same combat song going over any over. Any ideas? It's only since I updated this mod.

**Comment by ghyujkilop** [comment]
The only way to fix is to restart the game. [Here's my modlist](https://modwat.ch/u/mattski123).
