### ISSUE TITLE
Reproducible crash on switching shouts in beta 6 for AE

### ISSUE THREAD

**Issue by reynoldsa** [aers/EngineFixesSkyrim64#38]
On the latest beta, switching shouts in any menu, favourites or the main one, causes a game crash. Disabling the Engine Fixes mod causes this to stop. Crash dump from SKSE:

https://1drv.ms/u/s!AkNTVs1t-_7qjzeRnJSUr8du_tIO?e=KPyIhn

**Comment by aers** [comment]
Thanks.
