### ISSUE TITLE
Update new verison pls

### ISSUE THREAD

**Issue by Landate** [aers/EngineFixesSkyrim64#47]
@[aers](https://www.nexusmods.com/skyrimspecialedition/users/2025634) Pls update mod for new version Skyrim AE @aers 
Pls update mode for 1.6.629

**Comment by BullOnMars** [comment]
STFU

**Comment by aers** [comment]
I'm retired from Skyrim right now.

I've also been informed there's maybe another hotfix patch coming soon(tm) and I'm not going to bother doing anything until that's out.
