### ISSUE TITLE
Skyrim 1.6.640 broke Engine Fixes

### ISSUE THREAD

**Issue by LithRakoon** [aers/EngineFixesSkyrim64#48]
New skyrim update broke all SKSE plugins by changing around the code, and now every SKSE plugin will need an update including SSE Engine fixes.
![image](https://user-images.githubusercontent.com/41258148/192391407-60dfb1e4-4fba-4ef9-861a-774dc871ff19.png)

**Comment by WDF00** [comment]
Anxiously awaiting news on whether or not this will be addressed.  A comment on Nexus page indicates original author may not be working on this and there's no indication of anyone else picking up the code to fix it.  Since this breaks my modded Skyrim, I am concerned.

**Comment by DjDarthyGamer** [comment]
same, im waiting, this is very important for my preset :)

**Comment by LithRakoon** [comment]
Has been updated on nexusmods
https://www.nexusmods.com/skyrimspecialedition/mods/17230?tab=files
