### ISSUE TITLE
Broken sound in 2.10.1.5.50

### ISSUE THREAD

**Issue by Manic020** [aers/EngineFixesSkyrim64#5]
Sound effects aren't playing with the new version of the mod enabled (footsteps, weapon sounds, ambient music, etc.).

**Comment by aers** [comment]
Can you disable everything 1 at a time and tell me which is breaking it? I don't have the game installed right now.

**Comment by Manic020** [comment]
Disabling MaxStdio appears to fix it.

**Comment by aers** [comment]
Okay. Have an idea whats up. Thanks.
