### ISSUE TITLE
1.6.1130 Crash with FormCaching patch

### ISSUE THREAD

**Issue by AndrejAndb** [aers/EngineFixesSkyrim64#62]
Crash very frequent with active FormCaching (and looks resolved after disable)

very frequent after PC die or after change cell (or random - not clear)

[crash-2023-12-16-16-20-56.log](https://github.com/aers/EngineFixesSkyrim64/files/13693216/crash-2023-12-16-16-20-56.log)

**Comment by epinter** [comment]
At this moment a crashlog with others mods active is not so useful. There are more mods broken than updated. Also, FasterHDT is a know cause of random crashes.

There's a way to reproduce this crash with just SSE Engine Fixes enabled, without any other mod ?

**Comment by AndrejAndb** [comment]
I will close this task. due to the fact that I was able to reproduce the problem on 1.6.640 (It is not exclusive for 1130)
(the reason is not yet clear, so far only some assumption that it probably related to engine fixes + dyndolod ng +/or maybe some other things. and still have assumption that disabling FormCaching is resolve it)
