### ISSUE TITLE
The exact dependencies and folder structure needed to actually build this aren't documented anywhere.

### ISSUE THREAD

**Issue by Akira13641** [aers/EngineFixesSkyrim64#9]
I figured it out the structure on my own, and that it needs SKSE and SSECommonLib, but the rest I'm not sure of. E.G. where does "Logger.h" come from, and so on.

**Comment by aers** [comment]
Sorry for late reply..

put this repo & commonlib in the skse64 solution folder and add them both to the solution

**Comment by Ryan-rsm-McKenzie** [comment]
this project uses cmake now
